# Generated by Django 6.0 on 2026-02-23 01:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('email_domain', models.CharField(blank=True, max_length=100, null=True)),
                ('verified_status', models.CharField(choices=[('verified', 'Verified'), ('unverified', 'Unverified'), ('blacklisted', 'Blacklisted')], db_index=True, default='unverified', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScamRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('weight', models.IntegerField()),
                ('is_negative', models.BooleanField(default=False, help_text='If true, reduces risk score')),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-weight'],
            },
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name_text', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField()),
                ('stipend', models.IntegerField(blank=True, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('source', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DetectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.IntegerField()),
                ('verdict', models.CharField(choices=[('genuine', 'Genuine'), ('suspicious', 'Suspicious'), ('scam', 'Scam')], db_index=True, max_length=20)),
                ('confidence', models.CharField(max_length=10)),
                ('checked_at', models.DateTimeField(auto_now=True)),
                ('internship', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detection', to='core.internship')),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=200)),
                ('details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.internship')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internship_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RuleContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=200)),
                ('score_added', models.IntegerField()),
                ('detection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='core.detectionresult')),
            ],
            options={
                'ordering': ['-score_added'],
            },
        ),
        migrations.AddIndex(
            model_name='internship',
            index=models.Index(fields=['created_at'], name='core_intern_created_bff6df_idx'),
        ),
        migrations.AddIndex(
            model_name='detectionresult',
            index=models.Index(fields=['verdict'], name='core_detect_verdict_b96ef1_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['created_at'], name='core_report_created_9527e7_idx'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(fields=('internship', 'user'), name='unique_user_report'),
        ),
    ]
