# Generated by Django 6.0 on 2026-03-26 23:48

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email_domain', models.CharField(max_length=255, unique=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('verified_status', models.CharField(choices=[('verified', 'Verified'), ('unverified', 'Unverified'), ('blacklisted', 'Blacklisted')], db_index=True, default='unverified', max_length=20)),
                ('domain_resolves', models.BooleanField(blank=True, db_index=True, null=True)),
                ('has_mx_record', models.BooleanField(blank=True, db_index=True, null=True)),
                ('domain_age_days', models.IntegerField(blank=True, null=True)),
                ('domain_last_checked', models.DateTimeField(blank=True, null=True)),
                ('reputation_score', models.IntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['verified_status'], name='core_compan_verifie_ee65f2_idx'), models.Index(fields=['created_at'], name='core_compan_created_d2faa2_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_company_name_ci'), models.CheckConstraint(condition=models.Q(('domain_age_days__gte', 0), ('domain_age_days__isnull', True), _connector='OR'), name='domain_age_non_negative')],
            },
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name_text', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('stipend', models.IntegerField(blank=True, null=True)),
                ('source', models.CharField(db_index=True, max_length=255)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('fingerprint', models.CharField(db_index=True, editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internships', to='core.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DetectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.FloatField()),
                ('probability', models.FloatField()),
                ('verdict', models.CharField(choices=[('genuine', 'Genuine'), ('suspicious', 'Suspicious'), ('scam', 'Scam')], db_index=True, max_length=20)),
                ('engine_version', models.IntegerField(db_index=True)),
                ('is_latest', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='core.internship')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=200)),
                ('details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.internship')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internship_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScamRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('weight', models.IntegerField()),
                ('is_negative', models.BooleanField(default=False)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-weight'],
                'indexes': [models.Index(fields=['active'], name='core_scamru_active_976972_idx')],
            },
        ),
        migrations.CreateModel(
            name='RuleKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
                ('field', models.CharField(choices=[('title', 'Title'), ('description', 'Description'), ('email', 'Email')], default='description', max_length=20)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='core.scamrule')),
            ],
        ),
        migrations.CreateModel(
            name='RuleContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_snapshot', models.IntegerField()),
                ('score_added', models.FloatField()),
                ('detection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='core.detectionresult')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.scamrule')),
            ],
            options={
                'ordering': ['-score_added'],
            },
        ),
        migrations.AddIndex(
            model_name='internship',
            index=models.Index(fields=['source'], name='core_intern_source_8b3f38_idx'),
        ),
        migrations.AddIndex(
            model_name='internship',
            index=models.Index(fields=['created_at'], name='core_intern_created_bff6df_idx'),
        ),
        migrations.AddIndex(
            model_name='internship',
            index=models.Index(fields=['fingerprint'], name='core_intern_fingerp_b7d801_idx'),
        ),
        migrations.AddIndex(
            model_name='internship',
            index=models.Index(fields=['status'], name='core_intern_status_4a75d3_idx'),
        ),
        migrations.AddIndex(
            model_name='internship',
            index=models.Index(fields=['is_active'], name='core_intern_is_acti_81bced_idx'),
        ),
        migrations.AddConstraint(
            model_name='internship',
            constraint=models.CheckConstraint(condition=models.Q(('company__isnull', False), ('company_name_text__gt', ''), _connector='OR'), name='internship_company_or_text_required'),
        ),
        migrations.AddConstraint(
            model_name='internship',
            constraint=models.CheckConstraint(condition=models.Q(('stipend__gte', 0), ('stipend__isnull', True), _connector='OR'), name='stipend_non_negative'),
        ),
        migrations.AddIndex(
            model_name='detectionresult',
            index=models.Index(fields=['internship', '-created_at'], name='core_detect_interns_13cd0a_idx'),
        ),
        migrations.AddIndex(
            model_name='detectionresult',
            index=models.Index(fields=['is_latest'], name='core_detect_is_late_7a2e5c_idx'),
        ),
        migrations.AddIndex(
            model_name='detectionresult',
            index=models.Index(fields=['verdict'], name='core_detect_verdict_b96ef1_idx'),
        ),
        migrations.AddIndex(
            model_name='detectionresult',
            index=models.Index(fields=['engine_version'], name='core_detect_engine__2a56ce_idx'),
        ),
        migrations.AddConstraint(
            model_name='detectionresult',
            constraint=models.CheckConstraint(condition=models.Q(('probability__gte', 0), ('probability__lte', 1)), name='probability_range'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(fields=('internship', 'user'), name='unique_user_report'),
        ),
        migrations.AddIndex(
            model_name='rulekeyword',
            index=models.Index(fields=['keyword'], name='core_ruleke_keyword_76dca8_idx'),
        ),
    ]
