# Generated by Django 6.0 on 2026-02-25 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='domain_age_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='domain_last_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='domain_resolves',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='has_mx_record',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scamrule',
            name='is_negative',
            field=models.BooleanField(default=False),
        ),
    ]
