# Generated by Django 6.0 on 2026-02-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_company_domain_age_days_company_domain_last_checked_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='internship',
            name='core_intern_created_bff6df_idx',
        ),
        migrations.AddField(
            model_name='internship',
            name='fingerprint',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, null=True),
        ),
    ]
