# Generated by Django 6.0 on 2026-02-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_internship_core_intern_created_bff6df_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='fingerprint',
            field=models.CharField(db_index=True, editable=False, max_length=64, unique=True),
        ),
    ]
