# Generated by Django 6.0 on 2026-02-28 08:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_internship_fingerprint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={},
        ),
        migrations.AlterModelOptions(
            name='internship',
            options={},
        ),
        migrations.AddField(
            model_name='company',
            name='reputation_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='scam_posts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='total_posts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='company',
            name='email_domain',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='verified_status',
            field=models.CharField(choices=[('verified', 'Verified'), ('unverified', 'Unverified'), ('blacklisted', 'Blacklisted')], default='unverified', max_length=20),
        ),
        migrations.AlterField(
            model_name='internship',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internships', to='core.company'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='company_name_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internship',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='internship',
            name='source',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='internship',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
