# Generated by Django 6.0 on 2026-02-28 10:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_company_options_alter_internship_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='internship',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='company',
            name='scam_posts',
        ),
        migrations.RemoveField(
            model_name='company',
            name='total_posts',
        ),
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='reputation_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='company',
            name='verified_status',
            field=models.CharField(choices=[('verified', 'Verified'), ('unverified', 'Unverified'), ('blacklisted', 'Blacklisted')], db_index=True, default='unverified', max_length=20),
        ),
        migrations.AlterField(
            model_name='internship',
            name='company_name_text',
            field=models.CharField(blank=True, default='unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='internship',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='internship',
            name='fingerprint',
            field=models.CharField(editable=False, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='internship',
            name='source',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['verified_status'], name='core_compan_verifie_ee65f2_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['created_at'], name='core_compan_created_d2faa2_idx'),
        ),
        migrations.AddIndex(
            model_name='detectionresult',
            index=models.Index(fields=['risk_score'], name='core_detect_risk_sc_fbdb15_idx'),
        ),
        migrations.AddIndex(
            model_name='internship',
            index=models.Index(fields=['source'], name='core_intern_source_8b3f38_idx'),
        ),
        migrations.AddIndex(
            model_name='internship',
            index=models.Index(fields=['created_at'], name='core_intern_created_bff6df_idx'),
        ),
        migrations.AddIndex(
            model_name='internship',
            index=models.Index(fields=['fingerprint'], name='core_intern_fingerp_b7d801_idx'),
        ),
        migrations.AddIndex(
            model_name='scamrule',
            index=models.Index(fields=['active'], name='core_scamru_active_976972_idx'),
        ),
        migrations.AddConstraint(
            model_name='internship',
            constraint=models.CheckConstraint(condition=models.Q(('company__isnull', False), ('company_name_text__gt', ''), _connector='OR'), name='internship_company_or_text_required'),
        ),
    ]
