# Generated by Django 6.0 on 2026-02-28 10:26

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_company_options_alter_internship_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='domain_resolves',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='has_mx_record',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='internship',
            name='fingerprint',
            field=models.CharField(db_index=True, editable=False, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='internship',
            name='source',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_company_name_ci'),
        ),
        migrations.AddConstraint(
            model_name='detectionresult',
            constraint=models.CheckConstraint(condition=models.Q(('risk_score__gte', 0), ('risk_score__lte', 100)), name='risk_score_valid_range'),
        ),
        migrations.AddConstraint(
            model_name='internship',
            constraint=models.CheckConstraint(condition=models.Q(('stipend__gte', 0), ('stipend__isnull', True), _connector='OR'), name='stipend_non_negative'),
        ),
    ]
