# Generated by Django 6.0 on 2026-02-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_company_domain_resolves_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='internship',
            name='internship_company_or_text_required',
        ),
        migrations.AlterField(
            model_name='detectionresult',
            name='confidence',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], db_index=True, max_length=10),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.CheckConstraint(condition=models.Q(('domain_age_days__gte', 0), ('domain_age_days__isnull', True), _connector='OR'), name='domain_age_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='internship',
            constraint=models.CheckConstraint(condition=models.Q(('company__isnull', False), ('company_name_text__regex', '\\S+'), _connector='OR'), name='internship_company_or_text_required'),
        ),
    ]
