# Generated by Django 6.0 on 2026-02-28 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_internship_internship_company_or_text_required_and_more'),
        ('core', '0009_add_company_reputation_trigger'),
    ]

    operations = [
    ]
