# Generated by Django 6.0 on 2026-02-28 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_merge_20260228_1646'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='internship',
            name='internship_company_or_text_required',
        ),
        migrations.AlterField(
            model_name='internship',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internships', to='core.company'),
        ),
        migrations.AddConstraint(
            model_name='internship',
            constraint=models.CheckConstraint(condition=models.Q(('company__isnull', False), ('company_name_text__gt', ''), _connector='OR'), name='internship_company_or_text_required'),
        ),
    ]
