# Generated by Django 6.0 on 2026-03-01 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_internship_internship_company_or_text_required_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='detectionresult',
            index=models.Index(fields=['verdict', '-risk_score'], name='core_detect_verdict_782565_idx'),
        ),
    ]
