# Generated by Django 6.0 on 2026-03-01 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_detectionresult_core_detect_verdict_782565_idx'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='detectionresult',
            new_name='verdict_risk_desc_idx',
            old_name='core_detect_verdict_782565_idx',
        ),
    ]
