# Generated by Django 6.0 on 2026-03-01 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_core_detect_verdict_782565_idx_verdict_risk_desc_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
                ('field', models.CharField(choices=[('title', 'Title'), ('description', 'Description'), ('email', 'Email')], default='description', max_length=20)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='core.scamrule')),
            ],
            options={
                'indexes': [models.Index(fields=['keyword'], name='core_ruleke_keyword_76dca8_idx')],
            },
        ),
    ]
