# Generated by Django 6.0 on 2026-03-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rulekeyword'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='report',
            name='core_report_created_9527e7_idx',
        ),
        migrations.AddField(
            model_name='detectionresult',
            name='engine_version',
            field=models.IntegerField(db_index=True, default=1),
        ),
        migrations.AddIndex(
            model_name='detectionresult',
            index=models.Index(fields=['engine_version'], name='core_detect_engine__2a56ce_idx'),
        ),
    ]
